### ISSUE TITLE
Chat history on code-retreat

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/code_retreat#2]
Chris Payne [2:37 PM]  
Hey Guys, @jweeks and @jeffh could we have a chat about “Code Retreat” and how best to handle it? Also, a brief explanation on what each one of these actually is would be great: 
Caveman Coder (45 minutes) - Coding with marker on the walls? Erase it all—do it again? How many times/for how long?
Navigator-Driver (30 mintues) - Pair programming, switching every ? minutes?
Silent Coder (15 mintues) - Only using slack/AIM
Flat Files (30 mintues) - ?
Sandi's Rules (30 minutes) - ? I assume these, thought I’m not sure I’d be able to explain #4 to them now: https://robots.thoughtbot.com/sandi-metz-rules-for-developers
Git Happens (30 minutes) - ? Do we just reset git randomly?
Hot Potato (30 minutes) - ? 
Free-for-all (60 minutes) - ?
Retro of the Day (15 minutes)
 robots.thoughtbot.com
Sandi Metz' Rules For Developers
Back in January, Sandi Metz introduced her rules for developers in a Ruby... 

Jeff Horn [8:00 PM]  
The day begins with a discussion of what code retreat is and what the focus is: learning. The point is not to build working software but to practice the same problem many times under a variety of constraints with different partners. Developers are paired during each round with someone they have not worked with yet that day. Each round is followed by a brief standup where the moderator asks what each pair learned from the exercise. Don't tell the developers right away, but they have to delete their code and start from scratch for each exercise. The times I've run it, I use the times as a rough guideline.

[8:00]  
@payne.chris.r: ^

[8:01]  
Each exercise is done once. Caveman coder is done once no laptops allowed only whiteboard. It's a good chance to brainstorm rules implementations etc. before starting the first exercise (caveman) summarize the rules for Conway on the whiteboard. Leave it up all day. Should only be about four lines. I've found a table as a summary works well.

[8:02]  
Navigator pilot switches at 15 minute mark. All day they should be using one screen through screen hero.

[8:03]  
You'll have to find a download link for screen hero. You'll also have to manually send invites. I usually do that first thing.

[8:03]  
Silent coder does not use IM! They can only use code comments to communicate.

[8:04]  
Flat files means low levels of indentation. The left margin of their code should be as close as possible to the left margin while still following longer indentation suggestions. This pushed them to use fewer loops and if statements.

[8:05]  
Sandi's rule number four doesn't apply since they aren't using rails.

[8:06]  
Git happens I like to roll random between 1-10 and get an array like 4,7,7,3 then I force a hit reset at 4, 7 after that, 7 after that, etc. I use the rap air horn for a sound effect. They dig it.

[8:06]  
I do total request live and play music all day. They like that too.

[8:07]  
Free for all is no restrictions. I don't remember what hot potato is. @jweeks ??

[8:07]  
Probably one computer switch randomly. Either that or switch one line at a time. I like the latter. @payne.chris.r did you look at the README source? It has HTML comments about running the day.

[8:08]  
@payne.chris.r: you'd be doing us all a solid if you could summarize all these notes on the wiki for the lesson. I'm happy to edit and add additional information as necessary. You can just start by dumping and pasting all this chat history into the wiki page.

Jason Weeks [8:24 PM]  
One computer/typist each person has 1-2 minutes to instruct the typist what to type

**Comment by payne-chris-r** [comment]
**Navigator-Driver** Thought of a few things on the fly and went with them. Have navigator-driver be 5 minutes, then switch who navigated and who drove. Then for the second iteration I gave them 10 minutes in each role before swapping. This happened organically with the lunch break in between, but I thought it was interesting to see how they felt with a different amount of time between swaps.

**Comment by payne-chris-r** [comment]
**Silent Coder** A lot of devs felt they only scratched the surface, and expressed wanting more time. Because of this I gave them 2 minutes to speak out loud about their problem and then they were back to silent coding for 5 minutes. I did this as an experiment and as a chance to verbally vomit ideas at the person at the helm.

**Comment by jeffh** [comment]
Hey, I think you tagged the wrong Jeff. I'm not Jeff Horn.

Have a nice day 😄

**Comment by payne-chris-r** [comment]
@jeffh. My b! Will the real @jrhorn424 please stand up!?

**Comment by RealWeeks** [comment]
@payne-chris-r If you look at the readme.md or the live edit on github you can see that explanation for each one.  They are commented with HTML comments which hides them in the readme when you see it online but can see it when editing or in Atom.

**Comment by RealWeeks** [comment]
@payne-chris-r Temporary close, will reopen after delivered. Do want to give away the surprised to the devs.
